apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetrace-backend
  labels:
    app: treetrace-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treetrace-backend
  template:
    metadata:
      labels:
        app: treetrace-backend
    spec:
      containers:
      - name: treetrace-backend
        image: asad313/treetrace-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: GEE_JSON_CONTENT
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: GEE_JSON_CONTENT
        - name: RESEND_API_KEY
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: RESEND_API_KEY
        - name: MONGO_URI
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: MONGO_URI
        - name: GROQ_API_KEY
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: GROQ_API_KEY 
        - name: AI_GATEWAY_API_KEY
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: AI_GATEWAY_API_KEY
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: CLOUDINARY_API_SECRET 
        - name: CLERK_PUBLISHABLE_KEY
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: CLERK_PUBLISHABLE_KEY
        - name: CLERK_SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: treetrace-backend-secret
              key: CLERK_SECRET_KEY                               

---
apiVersion: v1
kind: Service
metadata:
  name: treetrace-backend-service
spec:
  selector:
    app: treetrace-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000