apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@treetrace.tech  # Change to your real email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx